### ISSUE TITLE
Could someone please post the compiled exe?

### ISSUE THREAD

**Issue by dalydir** [altf4/untwister#22]
Having problems with compiling programs right now, mind posting the compiled exe please?

**Comment by altf4** [comment]
We don't currently support windows, so that might be your issue with compiling!

**Comment by dalydir** [comment]
I meant with regards to compiling in C++ to begin with (not unique to your program), but fair enough.  I do have Python setup but all I see are .h and .cpp files, no .py's  Or am I thoroughly unable to run it on a windows machine even with python?

**Comment by altf4** [comment]
Untwister is not a python program, we just have some python bindings to exercise some functionality from python. Untwister is primarily a C++ program and needs to natively compile.
