### ISSUE TITLE
Errors in TestUntwister - make tests ./untwister_tests 

### ISSUE THREAD

**Issue by NewtoCScience** [altf4/untwister#27]
Hello, conducting the make tests .untwister_tests and received lines of errors. A lot of unqualified id, was not declared, expected primary-expression and others from the ./tests/TestUntwister.cpp. 

I used the code direct from Untwister. I attached screenshots of the Ubuntu terminal in order(sorry no # lines) and the TestUntwister.cpp for any mishaps I cannot see. All help is greatly appreciated, thank you! I would like to get past these errors to compile. 

![terminal1](https://cloud.githubusercontent.com/assets/11252214/6632060/763dff64-c8ed-11e4-8d1e-86aaf3e56f04.jpg)
![terminal2](https://cloud.githubusercontent.com/assets/11252214/6632061/7aad91a4-c8ed-11e4-9950-1a29219f0e39.jpg)
![terminal3](https://cloud.githubusercontent.com/assets/11252214/6632062/80c86ca8-c8ed-11e4-9500-3faf86f055ad.jpg)
![terminal4](https://cloud.githubusercontent.com/assets/11252214/6632064/864d1cf0-c8ed-11e4-88ff-5d8fc2d4362f.jpg)
![terminal5](https://cloud.githubusercontent.com/assets/11252214/6632069/8d644b6c-c8ed-11e4-8371-3e19cc244f6e.jpg)
![terminal6](https://cloud.githubusercontent.com/assets/11252214/6632071/90bb4892-c8ed-11e4-962e-c74565a8ed68.jpg)
![terminal7](https://cloud.githubusercontent.com/assets/11252214/6632074/94b62f20-c8ed-11e4-8014-d916ccc23c40.jpg)
![terminal8](https://cloud.githubusercontent.com/assets/11252214/6632075/99095a2a-c8ed-11e4-96ac-8ba2435498e8.jpg)
![terminal9](https://cloud.githubusercontent.com/assets/11252214/6632076/9ce70232-c8ed-11e4-956f-1fda1fb52d4e.jpg)
![testuntwister](https://cloud.githubusercontent.com/assets/11252214/6632092/cb5cb5b2-c8ed-11e4-96af-500a8cfc77ae.jpg)
![testuntwister2](https://cloud.githubusercontent.com/assets/11252214/6632094/cfa945f4-c8ed-11e4-8d0a-62255a4785ea.jpg)
![testuntwister3](https://cloud.githubusercontent.com/assets/11252214/6632096/d45e59ea-c8ed-11e4-96a8-a2cf7f49ff1f.jpg)
![testuntwister4](https://cloud.githubusercontent.com/assets/11252214/6632106/04832330-c8ee-11e4-87c1-6ae732b580e4.jpg)
![testuntwister5](https://cloud.githubusercontent.com/assets/11252214/6632108/0b1cd538-c8ee-11e4-98c7-ff360eb5b33f.png)
![testuntwister6](https://cloud.githubusercontent.com/assets/11252214/6632112/0f863d08-c8ee-11e4-9bdc-290ad1006954.png)

**Comment by altf4** [comment]
I just tried installing and building untwister from a fresh Ubuntu VM to double check that the whole process works, and it went fine for me. Just follow the steps in the readme, basically, but here it is again, with a little more detail:

```
mkdir Code
cd Code
sudo apt-get install python-dev libboost-python-dev libcppunit-dev git build-essential
git clone https://github.com/altf4/untwister.git
cd untwister
make
./untwister
```
